version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-multi-agent
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/backend/data
      - ./functions:/app/backend/functions
      - ./config.yaml:/app/backend/config.yaml
    environment:
      # n8n Configuration
      - N8N_BASE_URL=${N8N_BASE_URL:-http://n8n:5678}
      - N8N_API_KEY=${N8N_API_KEY}

      # LLM Provider API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}

      # Database
      - DATABASE_URL=${DATABASE_URL}

      # Security
      - JWT_SECRET=${JWT_SECRET}

      # Features
      - ENABLE_RAG=${ENABLE_RAG:-true}
      - ENABLE_WEB_SEARCH=${ENABLE_WEB_SEARCH:-true}
      - ENABLE_IMAGE_GENERATION=${ENABLE_IMAGE_GENERATION:-true}

      # Server
      - HOST=0.0.0.0
      - PORT=8080

    restart: unless-stopped
    networks:
      - multi-agent-network

  # Optional: n8n service
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-changeme}
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://n8n:5678/
    restart: unless-stopped
    networks:
      - multi-agent-network

  # Optional: Ollama for local models
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - multi-agent-network

volumes:
  n8n_data:
  ollama_data:

networks:
  multi-agent-network:
    driver: bridge
