services:
  - type: web
    name: brandfactory
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: standard  # $25/month with 2GB RAM (needed for Open WebUI)

    # Persistent storage for database, uploads, and models
    disk:
      name: openwebui-data
      mountPath: /app/backend/data
      sizeGB: 10

    # Environment variables
    envVars:
      # API Keys - SET THESE IN RENDER DASHBOARD (keep them secret!)
      - key: OPENAI_API_KEY
        sync: false

      - key: ANTHROPIC_API_KEY
        sync: false

      # N8N Integration
      - key: N8N_BASE_URL
        value: https://n8n-zdpc.onrender.com

      - key: N8N_API_KEY
        value: ""

      # BrandFactory Branding Configuration (Landing Page Approach)
      # Note: Landing page shows 100% BrandFactory, workspace shows Open WebUI
      - key: WEBUI_NAME
        value: "BrandFactory"

      - key: WEBUI_URL
        value: "https://brandfactory.onrender.com"

      - key: WEBUI_FAVICON_URL
        value: "/brandfactory/brandfactory-logo.png"

      # Database and data directory
      - key: DATA_DIR
        value: "/app/backend/data"

      # Open WebUI Configuration
      - key: WEBUI_SECRET_KEY
        generateValue: true

      # Disable memory-intensive features for 512MB plan
      - key: ENABLE_RAG
        value: "false"

      - key: ENABLE_WEB_SEARCH
        value: "false"

      - key: ENABLE_IMAGE_GENERATION
        value: "false"

      - key: ENABLE_VOICE
        value: "false"

      # Disable embedding models to save memory
      - key: RAG_EMBEDDING_ENGINE
        value: ""

      - key: RAG_EMBEDDING_MODEL
        value: ""

      # Server Configuration
      - key: PORT
        value: "8080"

      - key: HOST
        value: "0.0.0.0"

      # Optional: Ollama (if you want local models)
      - key: OLLAMA_BASE_URL
        value: ""

    # Health check endpoint
    healthCheckPath: /health

    # Auto-deploy on git push
    autoDeploy: true
